### ISSUE TITLE
Opening Extended Tuning does nothing

### ISSUE THREAD

**Issue by wucke13** [diydrones/apm_planner#1159]
When being connected to my AC 3.6.0 copter, opening the Extended Tuning page does nothing (the area where the parameters should be displayed stays blank). Switching to another view works just fine. I couldn't see any Debug messages in the console. Using Mission Planner on with the very same copter works, even the Extended Tuning.

**Comment by Arne-W** [comment]
This bug has been already fixed on master with this commit 89592371c877dbede468fc1ef73a52ca2111b7ce. If you are able to build a version from master it should fix that problem - otherwise you will have to wait a little bit. We will do a new release in the near future.
