### ISSUE TITLE
Add Joystick Support

### ISSUE THREAD

**Issue by billbonney** [diydrones/apm_planner#144]
Add joystick support using the RC_OVERIDE mechanism. The current implementation uses the MAVLink Manual Control message, which APM does not support AFAIU

**Comment by makuser** [comment]
What's the current status of this? The button still doesn't exist but when using the Joystick mapper panel I'm able to read the joystick.

**Comment by billbonney** [comment]
Joystick code was added with https://github.com/diydrones/apm_planner/commit/dc9ae8802311d110562bc3dfb536a8a816d148a3

**Comment by makuser** [comment]
@billbonney so then how do I enable the joystick input? The button that once was there (under "Actions") is gone.

**Comment by billbonney** [comment]
There is an option under the File menu. I haven't tested the code, so please report what issue you have and we will try to get them resolved. Thx :+1:

**Comment by makuser** [comment]
Yes and now? I see my joystick inputs and can map the joystick channels to x, y, z, throttle, and so on....
I just can't activate this joystick. I only see those values on the joystick screen. But it will not be sent to the vehicle (RC_OVERRIDE as well as MANUAL_CONTROL won't be sent).

In APM planner there's a button in the 'Actions' tab to activate the joystick (I guess...). I wasn't able to try that, because don't run windows myself and on the only windows machine I got access to, throws errors as soon as I hit the joystick button.

**Comment by makuser** [comment]
Sry I meant in mission planner there is a button for it. In APM planner v2+ there isn't any. There just is a menu entry for joystick mapping without actually enabling it.

Tested on v2.0.16@Ubuntu14.04 and v2.0.15@MacOSX10.10.1

**Comment by makuser** [comment]
@billbonney I don't really want to push you into anything, but I just want to ask you if you are onto this? Can I help you with something?

**Comment by billbonney** [comment]
I'll see if I have something that's joystick compatible with my computer hanging around, or if I can connect a PS3 controller using the same feature. My real reason for not investigating is not having a joystick

**Comment by makuser** [comment]
Thanks man :) there are also a lot of emulators available for both Linux and Windows. What are you running?

**Comment by makuser** [comment]
@billbonney anything I can help you with? Do you know of any other ground station software that *supports joystick commands in its current version*?

**Comment by nbrachet** [comment]
@makuser to "activate" the joystick you have to click the button in the Joystick. It will then send RC_OVERRIDE messages. This allows you to give control back to the transmitter if needed.

**Comment by billbonney** [comment]
I've split the 'joystick name'/deactivate/activate button out into seperate UI entities. see 6593e7b

You can pick up a daily build with the changes to test see http://firmware.diydrones.com/Tools/APMPlanner/daily/

**Comment by billbonney** [comment]
Woa, hang on! I just checked the code, and it looks like the full PR was merged in. Not sure why. I'll go back and pull in the extra changes. I'll let you know when it's fixed.

**Comment by billbonney** [comment]
Ok, this issue seems that I missed some changes to uas.cc in this commit https://github.com/nbrachet/apm_planner/commit/98b3e2fb7d764a0b2243842174965adb7efe5d44#diff-ff6f0e8f96c8b65ee73924f60debbb8e D'oh

**Comment by billbonney** [comment]
@makuser Ok, i just been over the changes, and it should work (my review using a mobile web browser didn't though). The merge looks good. I'll need to grab a PS3 joystick to test this properly though

**Comment by billbonney** [comment]
I have just tested this and have flown SITL Copter3.3rc6 using a PS3 controller on my Mac OSX 10.10.3

Works best in position hold or some other mode where half throttle is meaning no ascent/descent

**Comment by billbonney** [comment]
here's the settings for using the PS3 Joytick. It's a bit sensitive, but it works.
The mode buttons don't work, I used the Info View Action tab to change modes.

Now to have this displayed through CCRCSIM would be just awesome ;)

![joystick](https://cloud.githubusercontent.com/assets/959994/7903121/5ad78550-0787-11e5-8673-b89111b771a4.png)
