### ISSUE TITLE
Graph corruption, the nagative value is not visible in log.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#193]
I loaded this log: http://flyfoto-nord.no/baro_alt.-log    (renamed extension for webserver)
I cannot explain the huge, negative value that makes the altitude graph useless by scaling.

![screenshot from 2014-02-05 13 45 47](https://f.cloud.github.com/assets/1468842/2087024/fcf4e218-8e63-11e3-87ed-ac36ff791bd1.png)

- BTW: this log is downloaded using MP, my issues with connecting to terminal in planner2 remain.

**Comment by Arne-W** [comment]
I do not think we should filter values even if invalid cause it could suppress information that could be useful for analysing.
Issue should be closed.
