### ISSUE TITLE
Graph Time wrong

### ISSUE THREAD

**Issue by DerFlash** [diydrones/apm_planner#230]
While debugging a flight I've created a little table with times when what happened.
I've noticed that the time of the actions from my video and the GPS TimeMS line up perfectly, but the time shown from the APM Planner itself is absolutely wrong/nonsense.

https://gist.github.com/DerFlash/9188968

Is this a bug or am I doing something wrong? I'm on a Mac if that information may help.

**Comment by Arne-W** [comment]
Current master supports time resolution on newer logs. I think this could be closed

**Comment by billbonney** [comment]
Thanks :+1:
