### ISSUE TITLE
Build error, missing sndfile.h

### ISSUE THREAD

**Issue by Jyang772** [diydrones/apm_planner#260]
src/audio/AlsaAudio.h:42:21: fatal error: sndfile.h: No such file or directory
compilation terminated.

This is the error I get when trying build APM Planner. 
I don't have qtmake-qt4 so I used qmake qgroundcontrol.pro

I am on Ubuntu 12.04 64bit

**Comment by pushkalb123** [comment]
sudo apt-get install libsndfile1-dev

solve this problem
