### ISSUE TITLE
Firmware update issue - unable to gain access to bootloader

### ISSUE THREAD

**Issue by Daniel-1276** [diydrones/apm_planner#267]
Hi,

I tried to upload 2.78b APM plane firmware and i am continuously receiving "unable to gain access to bootloader". No idea if this is a big issue, as APM is booting up correctly with new firmware version 2.78b. No idea if bootcode was, or has to be updated accordingly.

Hardware/Software used:
- APM 2.6 clone (purple board)
- Windows 7 and Windows 8 ( tried using two different computers with compatibility option "as admin")
- Mission Planner 2.0.7

![missionplanner2 0 7_001](https://f.cloud.github.com/assets/6966001/2430788/10301ba8-ad05-11e3-9ebb-eccaab6622bc.PNG)
![missionplanner2 0 7_002](https://f.cloud.github.com/assets/6966001/2430789/1301a5ae-ad05-11e3-8a8d-829a6b374faa.PNG)
![missionplanner2 0 7_003](https://f.cloud.github.com/assets/6966001/2430790/156f5ebc-ad05-11e3-9d15-30afa9cbcb51.PNG)
![missionplanner2 0 7_004](https://f.cloud.github.com/assets/6966001/2430791/17afce46-ad05-11e3-94ab-3b610c3546ee.PNG)

**Comment by ClaytonMendes** [comment]
Hello my friends, sorry for my English but I managed to solve this problem using the mission planner 1.3.75
I simply downloaded the firmware in my case it was for rover as the link https://firmware.ardupilot.org/Rover/stable-2.5.1/apm2/
then in the mission planner I went to setup > install firmware > Load custom firmware.
I selected the firmware I had downloaded and it was successful
I had tried to change the version of the mission planner, use the APMplanner and nothing worked, and I downloaded the firmware and loaded it with I explained
