### ISSUE TITLE
Ubuntu 14.04:  dependency not satisfiable

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#317]
Tried to install latest daily build: apm_planner_2.0.8-51-g2da0d7f_ubuntu64.deb

apmplanner2 depends on libopenscenegraph80; however:  Package libopenscenegraph80 is not installed.

Current Ubuntu release offers libopenscenegraph99  and libopenscenegraph-dev

**Comment by gmorph** [comment]
The two warnings have now been fixed by this PR
https://github.com/stephendade/apm_planner/commit/930d08a5719c566c73565634aba9a70172227a8a

**Comment by AndKe** [comment]
Same issue observed today on an freshly upgraded Ubuntu 16.04 (LTS)
the latest .deb 64 bit says:

apmplanner2 depends on libopenscenegraph80; however: Package libopenscenegraph80 is not installed.
The user already got libopenscenegraph99 and libopenscenegraph-dev
