### ISSUE TITLE
Compare Parameter Function Not Working

### ISSUE THREAD

**Issue by jasonmc44** [diydrones/apm_planner#360]
Unable to compare parameter files. Can't select a file to compare, they are grey'ed out.

**Comment by jasonmc44** [comment]
2.0.18-rc1, OSX 10.10.3 and my parameter files are also .param.

**Comment by billbonney** [comment]
Looks fixed to me with 2.0.18-rc2 (but rc1 should also be fine)
![paramfiles](https://cloud.githubusercontent.com/assets/959994/8447924/da569938-1f74-11e5-968e-5c97d475e948.png)
