### ISSUE TITLE
compiling on olimex A10

### ISSUE THREAD

**Issue by wunderlins** [diydrones/apm_planner#404]
Hi

I am trying to compile on an olimex A10 with debian linux (wheezy/7).

I have cloned the stable branch (and before master) and as per instruction from the Readme.md I have installed all dependencies trough apt.

running qmake-gt4 gave me some errors:

olimex@a10Lime:~/apm_planner$ time qmake-qt4 qgroundcontrol.pro
Project MESSAGE: Qt version 4.8.2
Project MESSAGE: Linux build x86
Project MESSAGE: Release flavor
Project MESSAGE: BASEDIR /home/olimex/apm_planner DESTDIR /home/olimex/apm_planner/release TARGET apmplanner2
Project MESSAGE: Skipping support for QUpgrade
Project MESSAGE: Including support for Linux OpenSceneGraph Qt
Project MESSAGE: Including support for OpenSceneGraph
Project MESSAGE: Skipping support for Google Earth
Project MESSAGE: Skipping support for Protocol Buffers
Project MESSAGE: Skipping support for libfreenect
Project MESSAGE: Adding ALGLIB /home/olimex/apm_planner/libs/alglib
Project MESSAGE: Skipping support for XBee
Project MESSAGE: Skipping support for Opal-RT
WARNING: permFolders.path is not defined: install target not created

WARNING: permFiles.path is not defined: install target not created

real    0m31.365s
user    0m21.440s
sys 0m1.320s

I was feeling lucky and ran `make` which ended in the following error:

g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DQ_LINUX_32 -D_TTY_NOWARN_ -D__STDC_LIMIT_MACROS -DGIT_COMMIT=2.0.13 -DGIT_HASH=58f426825a3b8485c5dfe2959d0a68397805a983 -DQT_NO_DEBUG -DMAVLINK_NO_DATA -DQGC_USE_ARDUPILOTMEGA_MESSAGES -DQGC_OSG_QT_ENABLED -DQGC_OSG_ENABLED -DNOMINMAX -DEXTERNAL_USE -DQTCREATOR_UTILS_LIB -DEXTERNAL_USE -DHAVE_LIBUDEV -DDATADIR=\"/share\" -DPKGDATADIR=\"\" -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_TESTLIB_LIB -DQT_SCRIPT_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtTest -I/usr/include/phonon -I/usr/include/qt4/QtWebKit -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -IQsLog -I/usr/include -I/usr/local/include -Ilibs/mavlink/include/mavlink/v1.0 -Ilibs/mavlink/include/mavlink/v1.0/ardupilotmega -Isrc/apps/mavlinkgen -Isrc/apps/mavlinkgen/ui -Isrc/apps/mavlinkgen/generator -I. -Iui -Igenerator -Ilibs/eigen -Ilibs/alglib -I. -I.. -Isrc/core -Isrc/internals -Isrc/internals/projections -Isrc/mapwidget -Ilibs/utils -Ilibs -Ilibs/opmapcontrol -Ilibs/qwt -Ilibs/serialport -Ilibs/thirdParty/quazip -I/usr/src/3rdparty/zlib -I. -Isrc -Isrc/ui -Isrc/ui/linechart -Isrc/ui/uas -Isrc/ui/map -Isrc/uas -Isrc/comm -Iinclude/ui -Isrc/input -Isrc/lib/qmapcontrol -Isrc/ui/mavlink -Isrc/ui/param -Isrc/ui/watchdog -Isrc/ui/map3D -Isrc/ui/mission -Isrc/ui/designer -Isrc/ui/configuration -Isrc/output -I/usr/include/qt4/phonon_compat -I/usr/X11R6/include -Ibuild-release/moc -Ibuild-release/ui -o build-release/obj/QGCWebView.o src/ui/QGCWebView.cc
In file included from src/ui/QGCWebView.cc:2:0:
build-release/ui/ui_QGCWebView.h:20:29: fatal error: QtWebKit/QWebView: No such file or directory
compilation terminated.
make: **\* [build-release/obj/QGCWebView.o] Error 1

any idea what is going wrong, am I missing some dependencies (it seems to compile just fine on a raspi)?

Thanks for any advice and cheers
-S

olimex@a10Lime:~/Desktop$ uname -a
Linux a10Lime 3.4.90+ #3 PREEMPT Tue Jun 10 09:17:04 EEST 2014 armv7l GNU/Linux

olimex@a10Lime:~/Desktop$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14)

**Comment by gmorph** [comment]
The two warnings have now been fixed by this PR.
https://github.com/stephendade/apm_planner/commit/930d08a5719c566c73565634aba9a70172227a8a
