### ISSUE TITLE
CompassMOT gets a strange result.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#427]
This is observed on Pixhawk with ArduCopter 3.1.5 connected using telemetry to current APM_planner (downloaded release).

Reproduce:
-I start Compassmot (press start button)  
-Raising throttle does not draw a curve or display any values. (motors do run)  , returning throttle to zero.
-Pressing "stop" does display some strange offsets with exponent. (displayed in popup window)
After this calibration, the COMPASS_MOTCT is still disabled, and all COMPASS_MOT_* are still zero.

**Comment by billbonney** [comment]
Did you mean to close this? Is it fixed?

**Comment by AndKe** [comment]
It's a while since I saw it, and could reproduce it since then , and now with AC3.3 rc*   - I am unable to reproduce - thought it was fixed :)
