### ISSUE TITLE
Dialogs broken in OSX Yosemite

### ISSUE THREAD

**Issue by zlite** [diydrones/apm_planner#496]
The Serial Port drop down doesn't appear at all on the main display in Mac OSX Yosemite and appears above the dialog in the second display. See below:
![d9tcek6fwcfup2teler8ou_gzhmwiv097sim6g-u6xe](https://cloud.githubusercontent.com/assets/18071/4688473/4ee7d380-567a-11e4-9c9a-ece378f3cf2f.png)

**Comment by zlite** [comment]
Do we have an ETA on this fix for Yosemite?

**Comment by billbonney** [comment]
The fix for the serial port crashing issue #511 is hopefully in Qt5.4.1 That release was supposed to be delivered January. I'll see if I can find out when that is now scheduled to be released. and see if I can get a beta build tested this week.

**Comment by zlite** [comment]
Resizing the window doesn't fix it for me, although I'm using the latest build. Was QT5.4.1 actually released?

**Comment by billbonney** [comment]
status of Qt5.4.1 http://blog.gmane.org/gmane.comp.lib.qt.releasing

**Comment by zlite** [comment]
QT 5.4.1 has been released. Time to revist this?

https://blog.qt.io/blog/2015/02/24/qt-5-4-1-released/

**Comment by zlite** [comment]
Bill, just checking in on this again. It's the last thing missing from a great APM Planner experience on OSX. So close!

**Comment by billbonney** [comment]
Qt5.4.1 works on my machine as expected, but then the binaries are built on machine. This issue is when the binaries are built on another machine and then downloaded and installed 'from the internet'. This is when you assign permission explicitly for the binaries to execute. The effort with this is updating the build servers to create that binary. I'll try and get to it this week.

**Comment by zlite** [comment]
Bill, just checking on this one again. It's the last bug tormenting me on OSX!

**Comment by billbonney** [comment]
New builds are based on Qt5.4.2, this issue is now resolved. :)
