### ISSUE TITLE
artifacts in ApmToolBar and (new)Primary Flight Display

### ISSUE THREAD

**Issue by madlabindustries** [diydrones/apm_planner#538]
When both the ApmToolbar and the new Primary Flight Display are present in the window, this causes artifacting in both, which can render the toolbar unreadable.
Removing the new Primary Flight Display resolves the artifacting in the toolbar.   The old Primary Flight Display does not seem to cause any issues with artifacting.
This is being run on a computer with Ubuntu 14.04 and Intel (Sandy Bridge) HD 3000 graphics.  This may be related to this bug in Qt, which causes issues like this one to appear when there are multiple QQuickViews present.
https://bugreports.qt-project.org/browse/QTBUG-38222

**Comment by billbonney** [comment]
Closing this issue as this is related to Qt and not APM Planner 2.0
