### ISSUE TITLE
Debian Installation Problem 

### ISSUE THREAD

**Issue by mlcomputer** [diydrones/apm_planner#540]
Hello,

i have a big problem with the installation from source.
I opend the terminal and i follow the command in readme but i stuck on this command: qmake qgroundcontrol.pro.
That is what happend:

michael@michael12:~/apm_planner$ qmake qgroundcontrol.pro
Project MESSAGE: Qt version 5.1.1
Project MESSAGE: Linux build x64_86
Project MESSAGE: Release flavor
Project MESSAGE: BASEDIR /home/michael/apm_planner DESTDIR /home/michael/apm_planner/release TARGET apmplanner2
Project MESSAGE: Skipping support for QUpgrade
Project MESSAGE: Using mavlink  + ardupilotmega
Project MESSAGE: Skipping support for OpenSceneGraph
Project MESSAGE: Skipping support for Google Earth
Project MESSAGE: Skipping support for Protocol Buffers
Project MESSAGE: Skipping support for libfreenect
Project MESSAGE: Adding ALGLIB /home/michael/apm_planner/libs/alglib
Project MESSAGE: Skipping support for XBee
Project MESSAGE: Skipping support for Opal-RT
Project MESSAGE: QTDIR /usr
Project ERROR: Unknown module(s) in QT: quick
michael@michael12:~/apm_planner$ 

Best regardes Michael

**Comment by gmorph** [comment]
The two warnings have now been resolved by this PR.
https://github.com/stephendade/apm_planner/commit/930d08a5719c566c73565634aba9a70172227a8a
