### ISSUE TITLE
Some values are stored/displayed with extra decimals (values under mouse)

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#550]
If you graph any time (*MS) varaible, like GPS/BARO.TimeMS    , or BARO.Press , GPS.NSats , MAG.Ofs*  or even MODE.Mode   - they all are displayed ending with .0000 when displayed in the "show values under mouse" box.

**Comment by Arne-W** [comment]
Is this still relevant?? Otherwise close.

**Comment by billbonney** [comment]
Probably not, i'll close
