### ISSUE TITLE
Show ERR, Show EV are great, but overlaps.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#552]
EV and Errors usually comes in in clusters,  - this is my testflight for loss of RC.
The long texts overlaps.
- I see they are at different Y position, maybe they could be arranged at slightly different Y offset for each message within the area ? like this :
```
-----------------------------------------------------------------
|   Error description
|                            error description
|              event description 
|                                            event description
|        mode                         mode    mode  
|------------------------------------------------------------------
```
![screenshot from 2014-12-16 23 15 32](https://cloud.githubusercontent.com/assets/1468842/5463047/b2586870-8579-11e4-856a-c3ec0217caeb.png)

**Comment by billbonney** [comment]
This has been fixed in 0c8ccafae16e410604f60a12f0b5c178385b7f73
