### ISSUE TITLE
Graph Control: Clear Selection from Tree View does not clear all

### ISSUE THREAD

**Issue by billbonney** [diydrones/apm_planner#563]
Clearing graphing elements from tree view is not reflected in items in Cgraph Control window, and leads to the issue that the ranges are screwed up in the graph view
![graphingcontrols](https://cloud.githubusercontent.com/assets/959994/5560456/ebcda480-8d3f-11e4-9c44-4436dad72f02.png)

**Comment by malcom2073** [comment]
@billbonney Can you verify this is still an issue? I am unable to reproduce this.

**Comment by billbonney** [comment]
1. Load a log
1. Graph mode using Tree View
1. Show Graph Controls
1. close controls or keep open
1. Clear Selection in Tree View

![modegraphissues](https://cloud.githubusercontent.com/assets/959994/6192409/729170ae-b366-11e4-9386-2d6429eb3a1a.png)
