### ISSUE TITLE
Data for yAxes in CompassMot dialog seem to be swapped

### ISSUE THREAD

**Issue by mvanbutselaar** [diydrones/apm_planner#586]
The data for the yAxes in the CompassMot dialog seem to be [swapped](https://github.com/diydrones/apm_planner/blob/master/src/ui/configuration/CompassMotorCalibrationDialog.cpp#L87-L88), see image.

Also, a legend or colored yAxes wouldn't hurt.

See: http://i.imgur.com/sQBqM2G.jpg

**Comment by billbonney** [comment]
Thanks for the report. I'll swap them to be correct and add color to the labels.

**Comment by billbonney** [comment]
you can get a build with the fix here http://firmware.diydrones.com/Tools/APMPlanner/daily/ in about an hour
