### ISSUE TITLE
File masks no longer working under Linux

### ISSUE THREAD

**Issue by hsteinhaus** [diydrones/apm_planner#587]
2.0.16 seems to conrain some change in the file name masks, e.g. for loading/saveing parameters in the full param list. 

The new mask ("*.param;*.txt") does no longer list any of the .param files in the directory. I guess this new mask is only matching on files named like "my_latest_params.param;*.txt". 

After removing "*.txt;", the .param files are shown again.

**Comment by billbonney** [comment]
The problem is the mask should be separated by a space, not a semi-colon

**Comment by billbonney** [comment]
Fixed in c2083245fe3cd9c37be13ee012c4451aec8e427c

**Comment by hsteinhaus** [comment]
The fix works perfectly here, thanks.
