### ISSUE TITLE
Preflight calibration: quick accel levelling missing

### ISSUE THREAD

**Issue by hsteinhaus** [diydrones/apm_planner#595]
Old releases of APM planner provided a feature called "preflight calibration". The feature was perfectly suited to quickly adjust accell trim with the vehicle placed on a horizontal surface. Recent releases show a dialog instead, only offering gyro, baro and radio trim calibration.

I used this feature very frequently, as even a slightly looser or tighter cable is enough to bring the soft-mounted Pixhawk slightly out of position, causing a drift in Stabilize. The full accell calibration is no replacement for this functionality, as running an accel calib in the field is really a pain with a bulky 10kg octo - this is a two-man job.

**Comment by billbonney** [comment]
Following this discussion https://groups.google.com/d/msg/drones-discuss/4_8FEwxwFqQ/tfy3E8JsRhoJ the option you have are as per Randy's comments.

Which version of FW are you using. If it 3.x selecting Gyro calibration will do the 1D access calibration (i.e. level) you are suggesting.

**Comment by billbonney** [comment]
This is related to the new feature #710
