### ISSUE TITLE
Text cut off in vehicle type screen

### ISSUE THREAD

**Issue by zlite** [diydrones/apm_planner#610]
On OSX. See below
![apm_planner_v2_0_16-rc1__chriss-macbook-air_local__192_168_1_208_](https://cloud.githubusercontent.com/assets/18071/6120996/589ad988-b091-11e4-8a99-5f87b4464281.png)

**Comment by billbonney** [comment]
fixed in RC3
![frameselection](https://cloud.githubusercontent.com/assets/959994/6121221/c381890c-b093-11e4-80db-e92f8b1ea2ce.png)
