### ISSUE TITLE
using opMapControl

### ISSUE THREAD

**Issue by deadlyboy** [diydrones/apm_planner#626]
hi .
i'm writing a program in QT5.4 and in this program i need a map that can be with this features :
1- it works offline(after fetching tiles)
2- use marker on it
3- get the latitude and longitude  ,with mouse click event and ....
4-zoom
and ....

after a lot of research and try, i decided to use apm planner's (or qgroundcontrol's)  map(because it is opensource and i don't want to use it commercially ). i'm out of time really , there is no time for investigation

is there any chances to show me how to add libraries and use this map in my project ??
any help would be grate , thanks

**Comment by billbonney** [comment]
You can use Open Source code commercially. You just need to publish your changes if your redistribute the code is main condition.

you may find this control much easier to use https://github.com/raptorswing/MapGraphics

I'm closing this request as this isn't really an issue with APM Planner code.
