### ISSUE TITLE
Terminal outputs strange characters, won't take input

### ISSUE THREAD

**Issue by jaredmoody** [diydrones/apm_planner#628]
I'm on os x 10.10.2, and I am making sure to connect within 30s of connecting power to the board. 

![apm planner v2 0 15 jared-lappy local 10 0 1 9 2015-02-21 01-19-01](https://cloud.githubusercontent.com/assets/27690/6313560/ab74a5c4-b967-11e4-98da-d77ac6c2fdf0.jpg)

**Comment by madfish01** [comment]
ArduCopter 3.2-rc1 9-May-2014
Changes from 3.1.4
 11) CLI removed from APM1/2 to save flash space, critical functions moved to MAVLink:

https://github.com/diydrones/ardupilot/blob/master/ArduCopter/ReleaseNotes.txt
http://diydrones.com/forum/topics/cli-giving-garbage-with-apm-2-6-with-3-2-firmware

**Comment by billbonney** [comment]
Thanks @madfish01 issue closed

**Comment by jaredmoody** [comment]
Ah, makes sense, thanks guys.
