### ISSUE TITLE
Add RC channel reverse boxes

### ISSUE THREAD

**Issue by zlite** [diydrones/apm_planner#641]
In MP, buttons to reverse a channel are part of the RC setup process. As far as I can tell, there are no such buttons anywhere in APM Planner, and you have to go into the full parameter list to reverse channels. Can such buttons be added to the RC config page, as it is with MP?

**Comment by billbonney** [comment]
They are part of plane but not copter. Unless they are not showing up for some reason in Plane?

**Comment by zlite** [comment]
I was looking for them in Rover, where they're not showing up.
