### ISSUE TITLE
segmentation fault after mavlink connect

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#644]
This kind of fault happens now and then, right after connection.

https://gist.github.com/AndKe/f2737c5ce8a60ea0c87e

**Comment by malcom2073** [comment]
can you type "bt" after it crashes to get a stack trace?

**Comment by AndKe** [comment]
here is a new crash:  propely logged.
Please tell me if some +DEBUG should be used during compilation, for more symbols or anything :) 
https://gist.github.com/AndKe/2b37799c7b4fc32118e3

**Comment by malcom2073** [comment]
AndKe: can you try out the branch michael_dev? (af4cc61d547e3e8b6f46d20cf39daf059869edb7) I pulled in https://github.com/diydrones/apm_planner/pull/627 which may fix it.

**Comment by AndKe** [comment]
It works very well, no crash.
tried a lot of connects /restart om planner+connects , but no crash.
I did experience a connect-but-no-data issue like https://github.com/diydrones/apm_planner/issues/645 - but no crash.

Thanks.

**Comment by malcom2073** [comment]
Closing this as fixed in (5a763084857e1306a8b4fa43a0d87ed2aab0c48d)
