### ISSUE TITLE
when .tlog is is open as log (not played back) - modes are not visualized.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#668]
"Show mode" checkbox is green, HEARTBEAT.custom_mode can be graphed, but is not decoded into readable markers.

**Comment by AndKe** [comment]
It may be related, but roll, pitch, yaw and maybe other values cannot be graphed properly, some appear as integers only , some are just "0"   - same tlog show proper values when loaded for playback.

**Comment by malcom2073** [comment]
Correct, tlogs don't have a MODE variable, they use custom_mode. We need a way to know what kind of vehicle a tlog is replaying for in order to correctly display custom_mode.

roll/pitch/yaw however should not be 0, I'll look at that.

**Comment by billbonney** [comment]
The heartbeat message contains the vehicle type

**Comment by Arne-W** [comment]
Made a fix :-)
