### ISSUE TITLE
Standard/Advanced/Full Parameter Control list not available

### ISSUE THREAD

**Issue by snowt33nshi** [diydrones/apm_planner#671]
when doing the initial setup for the apm2.6, the Standard/Advanced/Full Parameter Control were all available on apm planner under the config/tuning tab. this was using a direct usb to apm connection.

after the setup was complete, i disconnected the board from the pc and did a test. all was well.

i subsequently connected the apm to the apm planner and the advanced parameters list is no longer available on the config/tuning tab.

**Comment by billbonney** [comment]
You need to enable 'Advanced Mode' in the file Menu.

Please raise 'support issues' here first http://ardupilot.com/forum/viewforum.php?f=82 We will raise defects here when they are confirmed as such. Thx :+1:
