### ISSUE TITLE
"Show values under mouse" - shows often 4 decimals more than needed.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#674]
CURR.Curr , ATT.Roll : 4 decimals too much
GPS.RelAlt, and GPS.Spd    2 decimals too much 

Many more needs to be corrected in the same manner.  - if you tell me where, I can fix.

**Comment by billbonney** [comment]
maybe it should be fixed to show up to 4 decimals, not current fixed 4 decimals?

**Comment by AndKe** [comment]
yes

**Comment by AndKe** [comment]
my fix :  https://github.com/diydrones/apm_planner/pull/684

**Comment by AndKe** [comment]
fixed a while ago.
