### ISSUE TITLE
Request: Keyboard shortcut to upload changed parameters

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#675]
Whenever in full parameter list, or in an tuning windows with save button, please add "Ctrl-W" shortcut to   "write" to UAV ?   -Ctrl-S may be more intuitive.
- reducing mouse movement and time when tuning. - and removing the need to focus out of the parameter being adjusted.

**Comment by billbonney** [comment]
This is as easy fix, just go to the .ui file and add keyboard shortcut to the button. See the ArduPlanePidConfig.ui for example

**Comment by AndKe** [comment]
I will be out on a mission next few days, but hope to have a pull request ready on Tuesday on Wednesday.
Thank you.

**Comment by AndKe** [comment]
please accept my pull requests :)

**Comment by billbonney** [comment]
I will. Sorry been busy.

**Comment by billbonney** [comment]
These PRs have been pulled in, Thx
