### ISSUE TITLE
APM Planner 2.0.17 crash on Open

### ISSUE THREAD

**Issue by lvale** [diydrones/apm_planner#676]
Just simply trying to open APM Planner 2.0.17 on MacBook Pro late 2013 (dual GPU's) and sometimes it crashes. No Hardware connected either via USB or via BT.

edit: corrected version

A link for a crash report is here:
https://www.dropbox.com/s/mgbex4c8si13on1/apm%20planner%202015%20crash%20on%20open.txt?dl=0

**Comment by billbonney** [comment]
Please retest with 2.0.17, if you still have issues, feel free to reopen. thx

**Comment by lvale** [comment]
Sorry. Issue occurred with 2.0.17 not 2.0.15.

My mistake.

**Comment by billbonney** [comment]
I'd suggest downloading and re-installing. You will then re-affrim gatekeeper settings. I am not seeing this as an issue with 2.0.17 downloaded from the internet.

(I did see that 10.10.3 did update gatekeeper settings so that maybe the issue)

**Comment by lvale** [comment]
Apparently the OS X 10.10.3 update might be the cause, as you say, because the updates gatekeeper settings.
Re installed 2.0.17 and started APM Planner using the right mouse button.
![screen shot 2015-05-02 at 14 03 11](https://cloud.githubusercontent.com/assets/3130363/7441177/15ba436e-f0d4-11e4-8ddd-f5b8068a01a4.png)
