### ISSUE TITLE
Mission elevation widget:  does not show anything in red, or add elevation.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#697]
Debug messages shows that it does get altitudes from Google just fine,  - but it does not seem to "use" it in any way.

DEBUG 2015-04-28T20:23:11.460 elevation loc:  69.6311 , 18.7309 
DEBUG 2015-04-28T20:23:11.460 elevation alt 4 : 0.242471 
DEBUG 2015-04-28T20:23:11.460 elevation loc:  69.6256 , 18.7133 
DEBUG 2015-04-28T20:23:11.461 elevation alt 5 : 21.6489 
DEBUG 2015-04-28T20:23:11.461 elevation loc:  69.6201 , 18.6957 
DEBUG 2015-04-28T20:23:11.461 elevation alt 6 : 75.2947 
DEBUG 2015-04-28T20:23:11.462 elevation loc:  69.6145 , 18.6782 
DEBUG 2015-04-28T20:23:11.462 elevation alt 7 : 122.357

**Comment by billbonney** [comment]
this is fixed with 10076e22d8ff85cba63c57cbb6e9dcb6a6d7af28

**Comment by AndKe** [comment]
Somehow, current master build, with this fix , does not graph anything (not even blue) in mission elevation widget, nor do I see any attempt to get the elevation in the console/log, or any error.

**Comment by billbonney** [comment]
I just tested with a loaded mission and I ahve this. You might need to be connected to a drone?
![elevationwidget](https://cloud.githubusercontent.com/assets/959994/7528011/25f22c4a-f4d7-11e4-8c39-19b2a55f2d81.png)

**Comment by AndKe** [comment]
Yes, now I see that it works fine when connected.
The mission does not need to  be on the UAV, it works with mission editor data.
Could you please make it work whithout a UAV connected ?

I guess MissionElevationDisplay::activeUASSet(UASInterface *uas) needs to be called from the end of MissionElevationDisplay::MissionElevationDisplay(QWidget *parent)    - but I am not sure about proper parameters.   

As a planning tool, we should not need an active connection for this widget to work.

**Comment by billbonney** [comment]
What you say makes sense. It requires using
`UASWaypointManager *UASManager::getActiveUASWaypointManager()` API to get a Waypoint manger before a UAS is connected.

One you have connected and disconnected you can still edit the waypoints, it's just that first connection creates a UAS object which hold the UASWaypointManager for the UAS.

**Comment by AndKe** [comment]
How can it be done ? Can something be called from MissionElevationDisplay::MissionElevationDisplay(QWidget *parent) , ? , or somewhere else ?
