### ISSUE TITLE
Maps caching

### ISSUE THREAD

**Issue by lvale** [diydrones/apm_planner#701]
While caching a larger area for offline usage APM Planner caches several zoom levels, which might take a long time....

While the time it takes is not "controlled" by APM Planner, one setting on APM Planner is kind of annoying, and could be changed.

Currently, after a zoom level is cached, APM Planner stops and asks if the following zoom level is to be cached and just sits there.....This dialog box could be eliminated of have a timeout with a default of yes (keep caching). MP on the other hand just goes to all zoom levels without asking.

It's irrelevant from which map provider this is done. On the pic I'm doing from Bing, because the coverage is newer than GGL :)

![screen shot 2015-05-02 at 03 07 21](https://cloud.githubusercontent.com/assets/3130363/7441200/fcafd4fa-f0d4-11e4-989d-6868ca86ef2e.png)

**Comment by billbonney** [comment]
Great suggestion. The map caching dialog can be improved for sure.

**Comment by lvale** [comment]
If improving the maps caching I would suggest something like:

Caching:
Zoom Start level: xx (number) yyyy (number of tiles - this can be retrieved rapidly from the maps provider)
Zoom Stop level : zz (number) wwww (number of tiles - this can be retrieved rapidly from the maps provider)
