### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#703]
Makefile:59587: recipe for target 'build-release/obj/MAVLinkDecoder.o' failed
make: *** [build-release/obj/MAVLinkDecoder.o] Error 1

all details here ;https://gist.github.com/AndKe/c30b44f0d4e32fc26efc

of course, the strangest thing is that nobody modified it lately..

**Comment by billbonney** [comment]
Clean build?

**Comment by AndKe** [comment]
Yes, I've even tried a fresh git clone before reporting.

**Comment by billbonney** [comment]
I've just tested on Linux 32Bit and OSX 64 Bit with a clean build and it works as expected.

This looks suspiciously like a bad merge https://gist.github.com/AndKe/c30b44f0d4e32fc26efc#file-gistfile1-txt-L18 into your branch. Are you using your master?

you can fix master to be exactly a copy of upstream using these instructions, try option2

(if you want to 'backup master' on your branch you can do
git checkout master
git checkout -b master_backup 
and that will create a branch that is a 'copy' of your master to backup_master

https://gist.github.com/billbonney/76de0f1a2e79f3a8a1a5

**Comment by AndKe** [comment]
I tried git checkout master  - it compiled, but not current version.
doing a git checkout upstream/master   fails to compile.   
(I do make clean every time while testing)  - what puzzles me , is that earlier today, I did:
git clone https://github.com/diydrones/apm_planner.git (to a new folder)
qmake qgroundcontrol.pro 
make -j8 
.. and failed too.

**Comment by billbonney** [comment]
I have fix (needed to use my linux 64bit machine to see the issue)

**Comment by AndKe** [comment]
thank you :)
