### ISSUE TITLE
libopenscenegraph80 dependency for Ubuntu-14-04

### ISSUE THREAD

**Issue by binarynut** [diydrones/apm_planner#715]
Where do I find dependency libopenscenegraph80 for install of Missionplanner on Ubuntu-14-04 ?

And I would imagine that libopenscenegraph80 would also have it's own dependencies.

**Comment by binarynut** [comment]
I stumbled across libopenscenegraph80 on the internet and got it installed.

And now a new problem, when I run ./Qgroundcontrol I get the error below;

./qgroundcontrol: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory

O will I ever get Qgroundcontrol working, I got a new build, Hexicopter and now I can't talk to it.

**Comment by billbonney** [comment]
I'm confused. I am building APM Planner 2.0 fine on 32bit Linux Mint 17.1 (based on 14.04) with Qt5.2.1 installed.

do you have libqt5declarative5 installed?

**Comment by harayz** [comment]
any update on this issue?

**Comment by billbonney** [comment]
This error usually means you have the wrong version of Qt installed, or haven't installed the dependencies. See https://github.com/diydrones/apm_planner/blob/master/README.md
