### ISSUE TITLE
Add new vendor cert

### ISSUE THREAD

**Issue by CraigElder** [diydrones/apm_planner#724]
please see https://github.com/diydrones/MissionPlanner/commit/45f2ee4924a29032ffdd05ef9aa92b5f75acaca9

**Comment by billbonney** [comment]
This is fixed for Windows with dfb0f76831b8fb188e5d5faa2ea1e9f47405e008 as it uses the PX4Uploader Binary from MP

**Comment by billbonney** [comment]
OSX and Linux Updated with 0b59fee
