### ISSUE TITLE
APM Planner creates the folder ~/apmplanner2 even if the AppData location is changed

### ISSUE THREAD

**Issue by pepak** [diydrones/apm_planner#730]
I changed the folder locations of App Data, Log output, tlog output and Parameters, but APM Planner still creates these folders:
~/apmplanner2
~/apmplanner2/dataflashLogs
~/apmplanner2/missions
~/apmplanner2/parameters
~/apmplanner2/tlogs

**Comment by billbonney** [comment]
The folder mapping are absolute. Not relative. This is more a 'feature' than a defect. This is so you can for example have logs in another location entirely from the app directory.

Having paths able to be set both relative to the App Directory setting or an absolute path would be ideal.

**Comment by pepak** [comment]
For clarification:
I changed the folder locations to:
APP_DATA_DIRECTORY=/home/user/.config/apmplanner2
LOG_DIRECTORY=/home/user/.config/apmplanner2/dataflashLogs
MAVLINK_LOG_DIRECTORY=/home/user/.config/apmplanner2/tlogs
MISSION_DIRECTORY=/home/user/.config/apmplanner2/missions
PARAMETER_DIRECTORY=/home/user/.config/apmplanner2/parameters

APM Planner still creates these empty folders that are not used:
/home/user/apmplanner2
/home/user/apmplanner2/dataflashLogs
/home/user/apmplanner2/missions
/home/user/apmplanner2/parameters
/home/user/apmplanner2/tlogs

During startup, the application should create the folder: /home/user/.config/apmplanner2 (if not exist), not /home/user/apmplanner2. I hope this is understandable, my English is not good.

**Comment by mrpilot2** [comment]
Hi, I have fixed this issue: 

The default directory passed when reading the settings file is only created if no other directory is found in the ini file (via the getters)

Furthermore I have added support to change the missions directory via GUI
