### ISSUE TITLE
Extended tuning screen swapped parameters 

### ISSUE THREAD

**Issue by jasonmc44** [diydrones/apm_planner#733]
Noticed that Stab_p and roll_p parameters are swapped in the extended tuning page. Running copter 3.3 rc5.

**Comment by billbonney** [comment]
Can you send  a screen shot, I don't see what you are seeing in APM Planner 2.0.18-rc1

**Comment by billbonney** [comment]
the build is here to test http://firmware.diydrones.com/Tools/APMPlanner/daily/2015-06-12/
