### ISSUE TITLE
Planner crashing while Armed

### ISSUE THREAD

**Issue by roldershaw** [diydrones/apm_planner#751]
Hi,

I'm running APM Planner v2.0.18-rc2 built from the latest commit on Xubuntu 14.04 and I'm getting crashes generally whilst in flight but also when I'm on the ground testing. I'm connecting using a third-party telemetry radio connected to an APM running the final firmware.

I've captured the terminal output from the program here http://pastebin.com/x6PrfWB0

Thanks.

**Comment by billbonney** [comment]
What version of Qt are you using?

**Comment by roldershaw** [comment]
Qt version 5.2.1

**Comment by mrpilot2** [comment]
Seems to be a duplicate of #648, which states a a bug in libxcb on Ubuntu 14.04

**Comment by roldershaw** [comment]
I'll try the workaround suggested in that issue and report back, thanks.

**Comment by roldershaw** [comment]
Flew for around an hour today with no crashes, thanks @mrpilot2 

https://gist.github.com/slimsag/a26d838ccc4480ce21bc resolved the issue.

**Comment by billbonney** [comment]
Thanks for the update. I wonder if we will get an official fix for LTS

**Comment by roldershaw** [comment]
Maybe at some point, there is an actual bug report for it here https://bugs.launchpad.net/ubuntu/+source/libxcb/+bug/1402966
So it should be actioned upon at some point, for now it may be an idea to write about this issue in the readme. The current release I'm on is Ubuntu 14.04.2 LTS
