### ISSUE TITLE
Extended Tuning horizontal "speed" labels swapped

### ISSUE THREAD

**Issue by jasonmc44** [diydrones/apm_planner#755]
Copter 3.2. Extended Tuning screen. "speed' and "loiter speed" labels are swapped. Adjusting "speed' value changes actual loiter speed and vice versa. I can even see it in the code but unsure of the process of editing it.

Thanks

Jason

**Comment by billbonney** [comment]
Thanks :+1:

**Comment by billbonney** [comment]
PS: see https://github.com/diydrones/apm_planner/blob/master/CONTRIBUTING.md for brief help on contributing and github help for more details
