### ISSUE TITLE
Commit 70b9a58 breaks display of log entries

### ISSUE THREAD

**Issue by walmis** [diydrones/apm_planner#774]
https://github.com/diydrones/apm_planner/commit/70b9a58b2cdfbd5a57d8799a062f26caf0ac93a6

This commit introduces integer divisions, which break display of log entries such as EKF3.IVD.
Since these values are fixed point integers, values less than 100 are rounded to 0.

**Comment by billbonney** [comment]
I'll make a fix for that. Thanks for the report
