### ISSUE TITLE
AC3.3 real-time vibration view

### ISSUE THREAD

**Issue by rmackay9** [diydrones/apm_planner#778]
![mp_vibedisplay_full](https://cloud.githubusercontent.com/assets/1498098/8971354/8f6d421e-368a-11e5-8b93-da3767da811a.png)

Mission Planner issue is here: https://github.com/diydrones/MissionPlanner/issues/948

**Comment by rmackay9** [comment]
This is the other item that I think is really important for the Copter-3.3 release.
https://github.com/diydrones/apm_planner/issues/779

**Comment by billbonney** [comment]
I've implemented Vibration Monitor, For now you open it from the 'Tools Widget' menu
![vibrationmonitor](https://cloud.githubusercontent.com/assets/959994/9701162/d00e17c0-53d2-11e5-997e-16008ce8c365.png)

**Comment by rmackay9** [comment]
Great!!!  AP2 users rejoice!
