### ISSUE TITLE
AC3.3: real-time EKF view

### ISSUE THREAD

**Issue by rmackay9** [diydrones/apm_planner#779]
![mp_ekf_full](https://cloud.githubusercontent.com/assets/1498098/8971383/c73f4002-368a-11e5-927c-b3316e01bd1c.png)

corresponding Mission Planner issue: https://github.com/diydrones/MissionPlanner/issues/949

**Comment by rmackay9** [comment]
We're getting close to the official Copter-3.3 release.  My guess is it'll go out within 3 weeks.  This EKF viewer and the vibration viewer are really important I think because it should allow users to know before hand if the EKF or vibration levels are serious enough that a crash or flyaway could result.

Bill & Co, I know you guys are busy but I just want to highlight the importance of these two items.

**Comment by billbonney** [comment]
This is in master

**Comment by rmackay9** [comment]
great news!  thanks!
