### ISSUE TITLE
Blank graph windows after loading a large BIN log file

### ISSUE THREAD

**Issue by lvale** [diydrones/apm_planner#789]
After loading a log file (BIN copied directly from the microSD) APMPlanner 2.0.18 presents a blank screen of the graph window, i.e. nothing to select and graph. It takes a long long time to load the file.

Bill, I can give you links to the bad behaved BIN files.

**Comment by lvale** [comment]
Just tested on the latest Windows version and its the same behavior. So both Mac and Win.

**Comment by lvale** [comment]
Well. It turns out that Copter RC9 saved 130MB blank log files.....So not a APM issue.

**Comment by billbonney** [comment]
Thanks for letting me know :+1:
