### ISSUE TITLE
Segfault on existing UDP data

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#802]
I run mavproxy like that:
./mavproxy.py --master=/dev/ttyACM1 --baudrate=115200 --out=udp:127.0.0.1:14550  

upon APM planner start, it arrarently recieves data, says "mode change ..." and crashes..
the funny part is that I did not connect, it "just works" on boot

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4eaebcb in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

If I start APM Planner first, then go to UDP settings, and click "disconnect" - I get:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4eed394 in QSocketNotifier::type() const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

- most likely related ?

**Comment by billbonney** [comment]
Odd. I use UDP all the time and o haven't been having that issue. But it's been on OSX. Another bug for Linux.

**Comment by billbonney** [comment]
Ok, this is pretty bad... I haven't been able to discover the reason yet. but it's only on Linux.

**Comment by AndKe** [comment]
yes, I think it's ironic, Linux being such a IP-orientated OS.  I suspect a
Qt bug.

**Comment by billbonney** [comment]
I tested with Qt 5.4.1, 5.4.2, 5.5.0 and they all behave the same. I might check older releases of AP2 to see if there is an older one that works. Finding the seg fault by brute force is seemingly impossible at the mo.

**Comment by AndKe** [comment]
Yes, I suspected it had to be a Qt bug, do we know where/how to submit it so the Qt devs are aware of it ?
