### ISSUE TITLE
Color selection in the "Graph Scale Control" dialog not working

### ISSUE THREAD

**Issue by marcpuig** [diydrones/apm_planner#815]
I'm using Qt version 5.4.1

The method AP2DataPlotAxisDialog::colorDialogAccepted is triggered when the colorSelected() signal is emitted, there's no need to check if the user has accepted or cancelled the dialog, according to the documentation it will emit only when the user has successfully selected the color and accepted the dialog.

To fix it delete the line 102 in the file ./src/ui/AP2DataPlotAxisDialog.cc

if (dialog->result() == QColorDialog::Accepted)

**Comment by billbonney** [comment]
Thx :+1:  I've add the fix.
