### ISSUE TITLE
Graphing logs not working on OS X El Capitan

### ISSUE THREAD

**Issue by jmachuca77** [diydrones/apm_planner#817]
I just upgraded my OS and it seems the log graphing is broken. Not 100% sure its due to the OS though.
![screen shot 2015-10-02 at 12 12 21 pm](https://cloud.githubusercontent.com/assets/1664405/10252733/159cfcfc-68ff-11e5-8170-799df3ca0137.png)

**Comment by jmachuca77** [comment]
That is a screenshot after loading a log.

**Comment by billbonney** [comment]
I just tested on OSX 10.11 and its working ok for me. Do you have more details on how to reproduce. ie APM Planner 2.0 version.
Also, try this build as it has some fixes in graphing (to color slection) http://firmware.diydrones.com/Tools/APMPlanner/daily/2015-10-01/apm_planner_2.0.18-35-g8fdbd34_osx.dmg

**Comment by jmachuca77** [comment]
Im using 2.0.17, and the log is a DF log from SOLO. I-ll try the new build.

**Comment by jmachuca77** [comment]
I just checked with the new build and it works fine.
