### ISSUE TITLE
Taranis telemetry stops working when AP2 connects

### ISSUE THREAD

**Issue by rmackay9** [diydrones/apm_planner#822]
Reported by Richard Kennedy on the Copter-3.3 beta testing discussion.
http://diydrones.com/forum/topics/copter-3-3-beta-testing?commentId=705844%3AComment%3A2107426&xg_source=msg_com_forum

**Comment by rmackay9** [comment]
Here's the discussion in the APM:Forum.
http://ardupilot.com/forum/viewtopic.php?f=111&t=13967&sid=2db8f1e6cae5b23c2c69f7f238659309

**Comment by billbonney** [comment]
You can set custom telemetry rates for AP2. I'm not sure why your teensy is failing, it could be that AP2 exposes messages it can't handle gracefully.
![telemetryrates](https://cloud.githubusercontent.com/assets/959994/10384272/8bee8798-6ded-11e5-927c-f5db43c7db50.png)

**Comment by billbonney** [comment]
The solution is probably to lower the attitude message rate to 5Hz and Extra 2 to 5Hz, in line with what the Teensy expects. The issue is with the teensy getting two many updates and not requesting what it needs from the autopilot. It's probably just swamped with messages

Not a defect,
