### ISSUE TITLE
Empty widgets for EKF and VIBE on latest RC4 running on OS X (10.11.1) and Linux (Ubuntu 15.04)

### ISSUE THREAD

**Issue by lvale** [diydrones/apm_planner#829]
they say a picture is worth a thousand words.....

<img width="1133" alt="screen shot 2015-10-26 at 15 01 14" src="https://cloud.githubusercontent.com/assets/3130363/10739297/7b4e10b4-7c13-11e5-960f-168a89566a64.png">

**Comment by lostcontrol** [comment]
Same on Linux (Ubuntu 15.04)

**Comment by billbonney** [comment]
I tested this as built from source and it works. Not sure why the packaged builds fail with no widgets. Needs investigation

**Comment by khancyr** [comment]
I confirmed that it is not working on ubuntu 15.04 , and windows (64bits)

**Comment by dcarpy** [comment]
It has something to do with the following (at run time):
DEBUG 2015-11-04T10:07:08.625  QUrl( "file:///usr/share/APMPlanner2/qml/VibrationMonitor.qml" )  
file:///usr/share/APMPlanner2/qml/VibrationMonitor.qml:54:9: Type BarGauge unavailable 
             BarGauge { 
             ^
file:///usr/share/APMPlanner2/qml/components/BarGauge.qml:3:1: module "QtQuick.Controls.Styles" is not installed 
     import QtQuick.Controls.Styles 1.2 
     ^
file:///usr/share/APMPlanner2/qml/components/BarGauge.qml:2:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 1.2 
     ^
file:///usr/share/APMPlanner2/qml/components/BarGauge.qml:3:1: module "QtQuick.Controls.Styles" is not installed 
     import QtQuick.Controls.Styles 1.2 
     ^
file:///usr/share/APMPlanner2/qml/components/BarGauge.qml:2:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 1.2 
     ^

**Comment by billbonney** [comment]
I'll take a look later. Please report Qt version when reporting Linux releases since that can be an issue. OSX Qt dependency is bundled with the package.

**Comment by dcarpy** [comment]
I've tested both Qt 5.2.1 and Qt 5.4.1 with the apm_planner_2.0.19-rc4-7-g0ce96ed_ubuntu_trusty64.deb daily build and both have the same issue.

**Comment by dcarpy** [comment]
Works great when I build on Windows using Qt 5.4.2.  Weird.

**Comment by billbonney** [comment]
I have fixed it for OSX (tested), Windows (still needs to be verified the new changes work)

**Comment by lvale** [comment]
@billbonney 
It does have content but it's not connected to data?

<img width="524" alt="screen shot 2015-11-10 at 19 24 07" src="https://cloud.githubusercontent.com/assets/3130363/11073089/ced4a18e-87e0-11e5-9cff-fb2d9b867644.png">
<img width="848" alt="screen shot 2015-11-10 at 19 22 36" src="https://cloud.githubusercontent.com/assets/3130363/11073088/ced0091c-87e0-11e5-8f02-34273907aca0.png">

**Comment by billbonney** [comment]
It's fixed for VIBE/EKF Monitor. The issue you are seeing is that the title bar gets out of sync with which link is connected. you may have another link connected. if you are connected with a real device, if you table you will see the vibration values change etc..

**Comment by lvale** [comment]
@billbonney 
You lost me.
There is only one PixHawk connected via USB. Opened the widgets and moved and resized them to the previous screen cap.

When selected they appear squashed to the right side of the screen

<img width="1440" alt="screen shot 2015-11-10 at 19 42 18" src="https://cloud.githubusercontent.com/assets/3130363/11073613/584e6286-87e3-11e5-9f40-9bdf0bfaa20d.png">

so I have to move them and resize them.

<img width="1431" alt="screen shot 2015-11-10 at 19 45 44" src="https://cloud.githubusercontent.com/assets/3130363/11073679/b1901d3a-87e3-11e5-8f60-4915bab10b84.png">


And the widgets "follow" no matter which screen we go they come :)

<img width="1432" alt="screen shot 2015-11-10 at 19 46 43" src="https://cloud.githubusercontent.com/assets/3130363/11073727/ef84c208-87e3-11e5-80d2-c1b54524a3c8.png">
<img width="1439" alt="screen shot 2015-11-10 at 19 46 32" src="https://cloud.githubusercontent.com/assets/3130363/11073729/efb46152-87e3-11e5-8a00-fb7fd0a54be7.png">
<img width="1431" alt="screen shot 2015-11-10 at 19 46 20" src="https://cloud.githubusercontent.com/assets/3130363/11073728/efb16d8a-87e3-11e5-90f7-a1025de6340a.png">

**Comment by lvale** [comment]
and even deselected they stay on screen:

<img width="1433" alt="screen shot 2015-11-10 at 19 53 41" src="https://cloud.githubusercontent.com/assets/3130363/11073949/deae2e1e-87e4-11e5-88e7-13f237a25da8.png">


btw:

OSX

<img width="585" alt="screen shot 2015-11-10 at 19 54 52" src="https://cloud.githubusercontent.com/assets/3130363/11073975/f9d4b992-87e4-11e5-8d24-b77047934ab7.png">

**Comment by billbonney** [comment]
This issue was closed. Please raise a new one for other issues. It's know issue, once the boxes have been resized, it remembered for the next run.

Try this build http://firmware.diydrones.com/Tools/APMPlanner/daily/2015-11-07/ as it seems to allow me to close the windows using the menu checklist (Please try latest daily first before posting an issue here)

You can resize the widgets when docked, and then they don't move to the other view, they only do that when undocked.

Post logs from ~/apmplanner2 folder is sometimes helpful.

If you write you use OSX10.10.1 I'll believe you, save yourself doing a screen grab everytime.
