### ISSUE TITLE
APM planner 2 crashes when I try to connect

### ISSUE THREAD

**Issue by abci-xeru** [diydrones/apm_planner#895]
Hello everyone

I have an issue, the APM planner 2 crashes everytime I click on connect , without even connecting it to my copter, the software itself crashes
Im using Ubuntu 14.04

any suggestions please ?

![screenshot from 2016-02-05 13 50 47](https://cloud.githubusercontent.com/assets/16308983/12846931/ff5c2f02-cc0f-11e5-873a-23412b01600a.png)

best regards

**Comment by billbonney** [comment]
please read the READEME https://github.com/diydrones/apm_planner/blob/master/README.md

Support questions are handled in the forum http://ardupilot.com/forum/viewtopic.php?f=82
