### ISSUE TITLE
Graph: visualize MSG mesages.

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#898]
Please add option to show MSG messages (strings) in graph.  very useful for planes.
Attaching screenshot to illustrate the kind of data we would see in graph.

![screenshot from 2016-02-06 20-27-11](https://cloud.githubusercontent.com/assets/1468842/12873249/d3e18d18-cdb8-11e5-8261-b9b2956fa8c8.png)

**Comment by billbonney** [comment]
@Arne-W You indicated you would like you work on this. Noted.
