### ISSUE TITLE
Graph View: Update graphing framework to actual version

### ISSUE THREAD

**Issue by Arne-W** [diydrones/apm_planner#904]
The version of the graphing framework we are using in Graph View is a little bit outdated. At the moment we are using V1.1.1 released at 09.12.2013 and the actual version is V1.3.2 released at 22.12.2015.
I think we should update to the new version before implementing new features on the old one. 

@billbonney What Do you think ?

**Comment by billbonney** [comment]
If you submit a pull request with it updated I will merge it in. Just make sure you test the Elevation Widget as that also uses the graph lib

**Comment by Arne-W** [comment]
That was easy :-)
I tested the Elevation widget and it looked normal to me - but I only have one tlog which I could use for testing. Perhaps somebody else should take a look.
